### ISSUE TITLE
BOM for original Tempest board

### ISSUE THREAD

**Issue by DirtyEngineer** [SupiSquirrel/Tempest#1]
I'd like to try assembling one of your original Tempest boards. Is there a BOM for it? I'm specifically trying to source the mosfet's (T1/T2), the zener diode (D4) and the schottky diode (D2).

Also can you clarify the purpose of the 22uf capacitor paralleled with the mosfet?

Any help would be much appreciated.

**Comment by SupiSquirrel** [comment]
Hi,

I updated the eagle files for Tempest for you. I added part #s for the fets and diodes.

Please note that 
- I also added a 100K resistor between the power switch and the controller "sense" pin. Without this resistor, when pushing the button, current flows over the clamp diodes trying to power the 3.3V rail, which results in a voltage that is too low to enable the voltage reg.
- I never tried the accelerometer and USB.

The 22uf cap (parallel to the mosfet in series with the solenoid, close to the solenoid connector) is intended to buffer the current drawn from the solenoid. I saw this on some commercial boards.

**Comment by DirtyEngineer** [comment]
Thanks for the update!  I really enjoy seeing your designs. Keep up the great work.
